DROP TABLE IF EXISTS DEVICE_UPTIME_TRACKER;
DROP TABLE IF EXISTS DEVICE_STATUS_TRACKER;
CREATE TABLE IF NOT EXISTS DEVICE_UPTIME_TRACKER
(
   DEVICE_ID VARCHAR(15) not null,
   DEVICE_NAME VARCHAR(250) not null,
   LOG_TIME TIMESTAMP not null,
   STATUS BIT not null,
   UP_TIME INT not null,
   DOWN_TIME INT not null
);
CREATE TABLE IF NOT EXISTS DEVICE_STATUS_TRACKER
(
   DEVICE_ID VARCHAR(15) not null,
   DEVICE_NAME VARCHAR(250) not null,
   LOG_TIME TIMESTAMP not null,
   STATUS BIT not null
);